OLD_PATH = "../old_LiveCodeBench/run_models_outputs/"

model_names = ['Claude-2',                                                                                                                
    'Claude-3-Haiku',                                                                                                          
    'Claude-3-Opus',                                                                                                           
    'Claude-3-Sonnet',                                                                                                         
    'Claude-Instant-1',                                                                                                        
    'Cllama-13b-Ins',                                                                                                          
    'Cllama-34b-Ins',                                                                                                          
    'Cllama-7b-Ins',                                                                                                           
    'CodeGemma-2b-Base',                                                                                                       
    'CodeGemma-7b-Base',                                                                                                       
    'CodeLlama-13b-Base',                                                                                                      
    'CodeLlama-34b-Base',                                                                                                      
    'CodeLlama-7b-Base',
    'Command-R',
    'Command-R+',
    'DBRX-Ins',
    'DSCoder-1.3b-Base',
    'DSCoder-1.3b-Ins',
    'DSCoder-33b-Base',
    'DSCoder-33b-Ins',
    'DSCoder-6.7b-Base',
    'DSCoder-6.7b-Ins',
    'GPT-3.5-Turbo-0125',
    'GPT-3.5-Turbo-0301',
    'GPT-3.5-Turbo-1106',
    'GPT-4-0314',
    'GPT-4-0613',
    'GPT-4-Turbo-1106',
    'GPT-4-Turbo-2024-04-09',
    'Gemma-2b-Base',
    'Gemma-7b-Base',
    'Google-Gemini-Pro',
    'Google-Gemini-Pro-1.5',
    'Google-Gemini-Ultra',
    'LLama3-70b-Base',
    'LLama3-70b-Ins',
    'LLama3-8b-Base',
    'LLama3-8b-Ins',
    'MagiCoderS-CL-7B',
    'MagiCoderS-DS-6.7B',
    'Mistral-Large',
    'Mixtral-8x22B-Ins',
    'Mixtral-8x7B-Ins',
    'OC-DS-1.3B',
    'OC-DS-33B',
    'OC-DS-6.7B',
    'Phind-34B-V2',
    'StableCode-3B',
    'StarCoder2-15b',
    'StarCoder2-3b',
    'StarCoder2-7b',
    'WCoder-33B-V1.1',
    'WCoder-34B-V1',
    ]

model_names = [    'GPT-4O-2024-05-13']

for model_name in model_names:
    !python -m lcb_runner.runner.custom_evaluator --custom_output_file {OLD_PATH}/{model_name}/chat_0.2.json --custom_output_save_name {model_name} --num_process_evaluate 80
    